version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  
jobs:
  build:
    docker:
      - image: circleci/mysql:8.0.4
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: springtestguide
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd
    steps:
      - checkout
      - mvn test
